# Generated by Django 3.0.14 on 2021-09-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='auteur',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='texte',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titre',
        ),
    ]
